module encoder_4to2_tb;
  
   reg D0,D1,D2,D3;
   wire Y0,Y1;

encoder_4to2 uut (

    .D0(D0),
    .D1(D1),
    .D2(D2),
    .D3(D3),
    .Y0(Y0),
    .Y1(Y1)
);

initial 
  begin 
       $monitor("D3=%b D2=%b D1=%b D0=%b -> Y1=%b Y0=%b",
          D3,D2,D1,D0,Y1,Y0);   
        D0 = 1; D1 = 0; D2 = 0; D3 = 0;
        #10;

       
        D0 = 0; D1 = 1; D2 = 0; D3 = 0;
        #10;

               D0 = 0; D1 = 0; D2 = 1; D3 = 0;
        #10;

                D0 = 0; D1 = 0; D2 = 0; D3 = 1;
        #10;
     $finish;
  end 
endmodule    

      

